# file: keys.yml
---
- hosts: all

  tasks:
  - name: Set up authorized_keys for the fenix user
    authorized_key: 
      user: root
      state: present
      key: "{{ lookup('file', '/Users/fenix/.ssh/id_rsa.pub') }}"
