# file: roles/common/tasks/main.yml
---
#Update and upgrade apt-based linux
- name: Update and upgrade apt-based Linux
  apt: update-cache=yes state=latest

- name: Install list of necessary packages
  apt: name={{item}} state=installed
  with_items:
       - git
       - libtool
       - build-essential
       - gcc 
       - autoconf
       - libpcre3-dev
       - libssl-dev
       - libcurl4-openssl-dev

